//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerFull.Tests.Messaging.Facade {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerFull.Tests.Messaging.Facade.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Current&quot;:{&quot;Total&quot;:0.0,&quot;PhaseA&quot;:0.0,&quot;PhaseB&quot;:0.0,&quot;PhaseC&quot;:0.0},&quot;Voltages&quot;:{&quot;AveragePhaseToNeutral&quot;:243.63,&quot;PhaseAToNeutral&quot;:243.63,&quot;PhaseBToNeutral&quot;:0.0,&quot;PhaseCToNeutral&quot;:0.0,&quot;AveragePhaseToLine&quot;:241.48,&quot;PhaseAToPhaseB&quot;:241.34,&quot;PhaseBToPhaseC&quot;:0.0,&quot;PhaseCToPhaseA&quot;:241.62,&quot;ACFrequency&quot;:49.97},&quot;RealPower&quot;:{&quot;Total&quot;:17.0,&quot;PhaseA&quot;:17.0,&quot;PhaseB&quot;:0.0,&quot;PhaseC&quot;:0.0},&quot;ApparentPower&quot;:{&quot;Total&quot;:666.0,&quot;PhaseA&quot;:666.0,&quot;PhaseB&quot;:0.0,&quot;PhaseC&quot;:0.0},&quot;ReactivePower&quot;:{&quot;Total&quot;:-666.0,&quot;PhaseA&quot;:-666.0,&quot;PhaseB&quot;:0.0,&quot;PhaseC&quot;:0.0},&quot;Po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Json {
            get {
                return ResourceManager.GetString("Json", resourceCulture);
            }
        }
    }
}
